---
title: "Report, Overall"
subtitle: "CAST"
author: "`r Sys.getenv('USERNAME')`"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: false
  word_document:
    toc: yes
  pdf_document:
    toc: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(results='asis', echo=FALSE, warning=FALSE)
# Debugging
boo.DEBUG <- FALSE
DEBUG.CaseNumber <- 1
#
if(boo.DEBUG==TRUE){##IF.boo.DEBUG.START
  if(DEBUG.CaseNumber==1){##IF.DEBUG.CaseNumber.START
    dir_results <- "C:\\Users\\Erik.Leppo\\OneDrive - Tetra Tech, Inc\\MyDocs_OneDrive\\GitHub\\CASTfxn\\Results"
  } else if(DEBUG.CaseNumber==2){
    dir_results <- "C:/Users/Erik.Leppo/OneDrive - Tetra Tech, Inc/MyDocs_OneDrive/AZ/"
  }##IF.DEBUG.CaseNumber.END
}##IF.boo.DEBUG.END
```

# REPORT INFORMATION
```{r report_date}
  myReportDate <- format(Sys.time(), "%Y-%m-%d %H:%M:%S")
  cat(paste("**Report Date and Time:** ",myReportDate,"\n\n",sep=""))
  myUser <- Sys.getenv("USERNAME")
  cat(paste("**Generated By:** ",myUser,"\n\n",sep=""))
  cat(paste("**CASTfxn Package Version:** ",packageVersion("CASTfxn"),"\n\n",sep=""))
```

# SITES

```{r Sites}
myPattern <- ".*(\\.map\\.jpg)$"
fn_target <- list.files(dir_results, pattern=myPattern, full.names=FALSE, recursive=TRUE)

x <- sort(unique(basename(fn_target)))
y <- sort(unique(gsub("\\.map\\.jpg$", "", x)))
y_len <- length(y)


cat(paste("**Site ID:** n = ",y_len,"\n\n",sep=""))
cat(y)
```
